In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.metrics import mean_absolute_percentage_error

## load the data

### action

In [2]:
# last column in action_filttune is the origin in filttune

action_CST_400 = np.loadtxt('data/action_in_CST_matrix_rand_seed400.csv',delimiter=',')
action_filttune_full_400 = np.loadtxt('data/action_in_filttune_matrix_19_seed400.csv',delimiter=',')

action_CST_500 = np.loadtxt('data/action_in_CST_matrix_rand_seed500.csv',delimiter=',')
action_filttune_full_500 = np.loadtxt('data/action_in_filttune_matrix_19_seed500.csv',delimiter=',')

action_CST_600 = np.loadtxt('data/action_in_CST_matrix_rand_seed600.csv',delimiter=',')
action_filttune_full_600 = np.loadtxt('data/action_in_filttune_matrix_19_seed600.csv',delimiter=',')

action_CST_700 = np.loadtxt('data/action_in_CST_matrix_rand_seed700.csv',delimiter=',')
action_filttune_full_700 = np.loadtxt('data/action_in_filttune_matrix_19_seed700.csv',delimiter=',')

action_CST_800 = np.loadtxt('data/action_in_CST_matrix_rand_seed800.csv',delimiter=',')
action_filttune_full_800 = np.loadtxt('data/action_in_filttune_matrix_19_seed800.csv',delimiter=',')

action_CST_900 = np.loadtxt('data/action_in_CST_matrix_rand_seed900.csv',delimiter=',')
action_filttune_full_900 = np.loadtxt('data/action_in_filttune_matrix_19_seed900.csv',delimiter=',')

action_CST_1000 = np.loadtxt('data/action_in_CST_matrix_rand_seed1000.csv',delimiter=',')
action_filttune_full_1000 = np.loadtxt('data/action_in_filttune_matrix_19_seed1000.csv',delimiter=',')

action_CST_1100 = np.loadtxt('data/action_in_CST_matrix_rand_seed1100.csv',delimiter=',')
action_filttune_full_1100 = np.loadtxt('data/action_in_filttune_matrix_19_seed1100.csv',delimiter=',')

action_CST_1200 = np.loadtxt('data/action_in_CST_matrix_rand_seed1200.csv',delimiter=',')
action_filttune_full_1200 = np.loadtxt('data/action_in_filttune_matrix_19_seed1200.csv',delimiter=',')

action_CST_1300 = np.loadtxt('data/action_in_CST_matrix_rand_seed1300.csv',delimiter=',')
action_filttune_full_1300 = np.loadtxt('data/action_in_filttune_matrix_19_seed1300.csv',delimiter=',')

In [3]:
action_filttune_400 = action_filttune_full_400[:,0:5372]
action_filttune_500 = action_filttune_full_500[:,0:3201]
action_filttune_600  = action_filttune_full_600[:,0:3636]

action_filttune_700 = action_filttune_full_700[:,0:855]
action_filttune_800 = action_filttune_full_800[:,0:482]

action_filttune_900  = action_filttune_full_900[:,0:1083]
action_filttune_1000 = action_filttune_full_1000[:,0:1068]
action_filttune_1100 = action_filttune_full_1100[:,0:2910]
action_filttune_1200 = action_filttune_full_1200[:,0:3878]
action_filttune_1300 = action_filttune_full_1300[:,0:4802]

### load screw positions

In [4]:
screw_pos_600  = np.loadtxt('data/screw_position_CST_matrix_random_600.csv',delimiter=',')
screw_pos_1200 = np.loadtxt('data/screw_position_CST_matrix_random_1200.csv',delimiter=',')
screw_pos_1300 = np.loadtxt('data/screw_position_CST_matrix_random_1300.csv',delimiter=',')

In [5]:
screw_pos_1300.shape

(19, 4802)

### load the RMSE data

In [6]:
#load the RMSE data.
#1st row: rmse; 2nd row: mrse
RMS_400  = np.loadtxt('data/RMS_seed400.csv',delimiter=',')
RMS_500  = np.loadtxt('data/RMS_seed500.csv',delimiter=',')
RMS_600  = np.loadtxt('data/RMS_seed600.csv',delimiter=',')
RMS_700  = np.loadtxt('data/RMS_seed700.csv',delimiter=',')
RMS_800  = np.loadtxt('data/RMS_seed800.csv',delimiter=',')
RMS_900  = np.loadtxt('data/RMS_seed900.csv',delimiter=',')
RMS_1000 = np.loadtxt('data/RMS_seed1000.csv',delimiter=',')
RMS_1100 = np.loadtxt('data/RMS_seed1100.csv',delimiter=',')
RMS_1200 = np.loadtxt('data/RMS_seed1200.csv',delimiter=',')
RMS_1300 = np.loadtxt('data/RMS_seed1300.csv',delimiter=',')

In [7]:
from tensorflow.keras.models import Sequential,load_model, clone_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization, Dropout
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, TensorBoard
from tensorflow.keras import regularizers
from tensorflow.keras.regularizers import l2, l1, l1_l2
from tensorflow.keras.losses import MeanAbsolutePercentageError
import tensorflow as tf

from livelossplot import PlotLossesKeras

from tensorflow.keras.models import Sequential,load_model, clone_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization, Dropout
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, TensorBoard
from tensorflow.keras import regularizers
from tensorflow.keras.regularizers import l2, l1, l1_l2

from livelossplot import PlotLossesKeras

2022-02-02 08:43:56.875850: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2022-02-02 08:43:57.545076: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer.so.7
2022-02-02 08:43:57.546105: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer_plugin.so.7


## Complete_small dataset

### Select the data with RMSE<0.09

In [8]:
index_400 = range(action_CST_400.shape[1])
temp_400 = RMS_400[0,:]>0.04
to_delete_400 = index_400*temp_400
to_delete_400 = [i for i in to_delete_400 if i != 0]

index_500 = range(action_CST_500.shape[1])
temp_500 = RMS_500[0,:]>0.09
to_delete_500 = index_500*temp_500
to_delete_500 = [i for i in to_delete_500 if i != 0]

index_600 = range(action_CST_600.shape[1])
temp_600 = RMS_600[0,:]>0.09
to_delete_600 = index_600*temp_600
to_delete_600 = [i for i in to_delete_600 if i != 0]

index_700 = range(action_CST_700.shape[1])
temp_700 = RMS_700[0,:]>0.09
to_delete_700 = index_700*temp_700
to_delete_700 = [i for i in to_delete_700 if i != 0]

index_800 = range(action_CST_800.shape[1])
temp_800 = RMS_800[0,:]>0.09
to_delete_800 = index_800*temp_800
to_delete_800 = [i for i in to_delete_800 if i != 0]

index_900 = range(action_CST_900.shape[1])
temp_900 = RMS_900[0,:]>0.09
to_delete_900 = index_900*temp_900
to_delete_900 = [i for i in to_delete_900 if i != 0]

index_1000 = range(action_CST_1000.shape[1])
temp_1000 = RMS_1000[0,:]>0.09
to_delete_1000 = index_1000*temp_1000
to_delete_1000 = [i for i in to_delete_1000 if i != 0]

index_1100 = range(action_CST_1100.shape[1])
temp_1100 = RMS_1100[0,:]>0.09
to_delete_1100 = index_1100*temp_1100
to_delete_1100 = [i for i in to_delete_1100 if i != 0]

index_1200 = range(action_CST_1200.shape[1])
temp_1200 = RMS_1200[0,:]>0.09
to_delete_1200 = index_1200*temp_1200
to_delete_1200 = [i for i in to_delete_1200 if i != 0]

index_1300 = range(action_CST_1300.shape[1])
temp_1300 = RMS_1300[0,:]>0.09
to_delete_1300 = index_1300*temp_1300
to_delete_1300 = [i for i in to_delete_1300 if i != 0]

In [9]:
action_CST_400_small  = np.delete(action_CST_400, to_delete_400,  axis=1)
action_CST_500_small  = np.delete(action_CST_500, to_delete_500,  axis=1)
action_CST_600_small  = np.delete(action_CST_600, to_delete_600,  axis=1)
action_CST_700_small  = np.delete(action_CST_700, to_delete_700,  axis=1)
action_CST_800_small  = np.delete(action_CST_800, to_delete_800,  axis=1)
action_CST_900_small  = np.delete(action_CST_900, to_delete_900,  axis=1)
action_CST_1000_small = np.delete(action_CST_1000, to_delete_1000,  axis=1)
action_CST_1100_small = np.delete(action_CST_1100, to_delete_1100,  axis=1)
action_CST_1200_small = np.delete(action_CST_1200, to_delete_1200,  axis=1)
action_CST_1300_small = np.delete(action_CST_1300, to_delete_1300,  axis=1)

action_filttune_400_small   = np.delete(action_filttune_400, to_delete_400,  axis=1)
action_filttune_500_small   = np.delete(action_filttune_500, to_delete_500,  axis=1)
action_filttune_600_small   = np.delete(action_filttune_600, to_delete_600,  axis=1)
action_filttune_700_small   = np.delete(action_filttune_700, to_delete_700,  axis=1)
action_filttune_800_small   = np.delete(action_filttune_800, to_delete_800,  axis=1)
action_filttune_900_small   = np.delete(action_filttune_900, to_delete_900,  axis=1)
action_filttune_1000_small  = np.delete(action_filttune_1000, to_delete_1000,  axis=1)
action_filttune_1100_small  = np.delete(action_filttune_1100, to_delete_1100,  axis=1)
action_filttune_1200_small  = np.delete(action_filttune_1200, to_delete_1200,  axis=1)
action_filttune_1300_small  = np.delete(action_filttune_1300, to_delete_1300,  axis=1)

In [10]:
screw_pos_600_small  = np.delete(screw_pos_600, to_delete_600,  axis=1)
screw_pos_1200_small = np.delete(screw_pos_1200, to_delete_1200,  axis=1)
screw_pos_1300_small = np.delete(screw_pos_1300, to_delete_1300,  axis=1)

## Small tol data 600, 1200, 1300

In [11]:
a_CST_small_ST13 = np.concatenate((action_CST_600_small,action_CST_1200_small,action_CST_1300_small),axis = 1)
a_filttune_small_ST13 = np.concatenate((action_filttune_600_small,action_filttune_1200_small,action_filttune_1300_small),axis = 1)

In [12]:
a_CST_small_ST13.shape

(19, 11767)

In [13]:
X_train_small_ST13, X_test_small_ST13, y_train_small_ST13, y_test_small_ST13 = train_test_split( 
     a_filttune_small_ST13.transpose(),a_CST_small_ST13.transpose(), random_state=1,train_size = 0.8)

## Load the model

In [14]:
model_small_ST13_0 = load_model('model/model_comp_small_ST13_0.h5')

2022-02-02 08:44:15.252987: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2022-02-02 08:44:15.906054: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-02 08:44:15.906846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2022-02-02 08:44:15.906937: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2022-02-02 08:44:15.906999: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2022-02-02 08:44:15.927338: I tensorflow/stream_executor/platform/default/d

In [25]:
#X_train_small_ST13.shape
model_small_ST13_0.predict(X_train_small_ST13[0,:].reshape(1,19))

2022-02-02 08:49:47.410834: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11


array([[ 0.19007073, -0.0297387 , -0.04670365, -0.12381869,  0.16737247,
        -0.13502488,  0.23246627, -0.00840205, -2.9792135 ,  0.79040307,
         1.4438162 , -1.8481365 , -1.0588993 ,  0.21899073, -1.9789106 ,
         0.78799677, -0.44349667,  0.55983305,  0.61877334]],
      dtype=float32)

In [24]:
X_train_small_ST13[0,:].reshape(1,19)

array([[ 62.1920771 , -10.29474562, -14.40919355, -36.53025982,
         23.001731  , -40.31690481,  34.2544795 , -25.15403911,
         37.40503833, -14.14665732,  -8.80901397,  28.83117668,
          3.69178567, -12.29770168,  62.53575754,  -1.06929525,
          8.00910815,  -5.20504093,  -2.81296213]])

In [14]:
y_train_predict_small_ST13 = model_small_ST13_0.predict(X_train_small_ST13)
y_test_predict_small_ST13 = model_small_ST13_0.predict(X_test_small_ST13)

2022-01-26 14:24:11.210458: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11


In [15]:
mse_train_small_ST13 = metrics.mean_squared_error(y_train_small_ST13, y_train_predict_small_ST13)
mse_test_small_ST13 = metrics.mean_squared_error(y_test_small_ST13, y_test_predict_small_ST13)

r2_train_small_ST13 = r2_score(y_train_small_ST13, y_train_predict_small_ST13)
r2_test_small_ST13 = r2_score(y_test_small_ST13, y_test_predict_small_ST13)

print("The model performance for testing set")
print("--------------------------------------")
print('MSE train is {}'.format(mse_train_small_ST13))
print('MSE test is {}'.format(mse_test_small_ST13))
print('R2 train is {}'.format(r2_train_small_ST13))
print('R2 test is {}'.format(r2_test_small_ST13))

The model performance for testing set
--------------------------------------
MSE train is 0.004427111576401967
MSE test is 0.01457841642056847
R2 train is 0.9832619914054623
R2 test is 0.9622657328997697


# The order of C-type screw in regression model and data is [c14 c58 c24 c57], but when implement it in CST, the order is [c14 c24 c57 c58]
## prepare test on CST
##### screw_pos_1300 - y_test_small_ST13 = golden_CST
##### check if screw_pos_1300 - y_test_predict_small_ST13 is close to golden_CST

In [16]:
golden_CST = np.array([0.627372, 0.849978, 0.950813, 0.875983, 0.866188, 1.03133, 0.671715, 0.085633, 1.69804,
                       0.508077, 0.803913, 1.08792, -0.844056, -0.484051, 1.71896, 0, 0, 0, 0]);

In [17]:
golden_CST

array([ 0.627372,  0.849978,  0.950813,  0.875983,  0.866188,  1.03133 ,
        0.671715,  0.085633,  1.69804 ,  0.508077,  0.803913,  1.08792 ,
       -0.844056, -0.484051,  1.71896 ,  0.      ,  0.      ,  0.      ,
        0.      ])

In [18]:
ind = 1;
ind_corresp = 354;

In [19]:
y_test_small_ST13[ind,:]

array([ 0.03993473, -0.00377502,  0.08463335,  0.1526819 , -0.10614267,
       -0.13636698,  0.17502374,  0.24649303, -2.50765423,  0.75339692,
        1.63199529, -0.07519394, -2.03732031, -1.46412542,  0.22647627,
       -0.08740146, -0.58218208, -0.6883281 , -0.8864348 ])

In [119]:
screw_pos_1300[:,ind_corresp]-golden_CST

array([ 0.03993473, -0.00377502,  0.08463335,  0.1526819 , -0.10614267,
       -0.13636698,  0.17502374,  0.24649303, -2.50765423,  0.75339692,
        1.63199529, -0.07519394, -2.03732031, -1.46412542,  0.22647627,
       -0.08740146, -0.58218208, -0.6883281 , -0.8864348 ])

In [120]:
# To see if screw_pos + true action = golden
screw_pos_1300[:,ind_corresp] - y_test_small_ST13[ind,:] - golden_CST

array([ 0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0., -0., -0.,  0., -0.,
        0., -0.,  0.,  0.,  0.,  0.])

In [121]:
# Predicted tuned_pos
np.set_printoptions(suppress=True)
screw_pos_1300[:,ind_corresp] - y_test_predict_small_ST13[ind,:]

array([ 0.62777688,  0.83638611,  0.94207557,  0.90080561,  0.87112645,
        0.9972801 ,  0.6569152 ,  0.13479114,  1.68552799,  0.55764273,
        0.78713653,  1.06944071, -0.76545862, -0.45124785,  1.78467314,
       -0.04438381,  0.03984514,  0.02737211, -0.02410752])

In [123]:
# the difference between predicted pos and golden pos
np.set_printoptions(suppress=True)
screw_pos_1300[:,ind_corresp] - y_test_predict_small_ST13[ind,:] - golden_CST

array([ 0.00040488, -0.01359189, -0.00873743,  0.02482261,  0.00493845,
       -0.0340499 , -0.0147998 ,  0.04915814, -0.01251201,  0.04956573,
       -0.01677647, -0.01847929,  0.07859738,  0.03280315,  0.06571314,
       -0.04438381,  0.03984514,  0.02737211, -0.02410752])

### find the index of the samples

In [65]:
tmp = action_filttune_1200.transpose()[:,0] == X_test_small_ST13[ind,0]
sum(tmp)

1

In [66]:
# find the specific action index in data
tmp = action_filttune_1200.transpose()[:,0] == X_test_small_ST13[ind,0]
index = 0
for i in tmp:
    if i == False:
        index += 1
        continue
    else:
        print(index)

1629


0  seed1300, 4407
1      1300,  354
2      1300,   2367
3      600,  3030
4      1200,  1972
5      1200, 1629

In [249]:
 - 1479.76 - 740

-2219.76

In [ ]:
# the predicted tuned filter

[ 0.60319551,  0.85670162,  0.95154853,  0.88269402,  0.86424006,
        1.04898076,  0.67292837,  0.087896  ,  1.52545837,  0.55680651,
        0.80771379,  1.02972063, -0.85833905, -0.52554665,  1.71641269,
        0.00707366, -0.023854  , -0.09192209, -0.04326849]

[ 0.62777688,  0.83638611,  0.94207557,  0.90080561,  0.87112645,
        0.9972801 ,  0.6569152 ,  0.13479114,  1.68552799,  0.55764273,
        0.78713653,  1.06944071, -0.76545862, -0.45124785,  1.78467314,
       -0.04438381,  0.03984514,  0.02737211, -0.02410752]

[ 0.60196096,  0.85464159,  0.96300044,  0.85892145,  0.86303518,
        1.05845897,  0.65048468,  0.09389948,  1.62563769,  0.44471845,
        0.89098338,  1.00822993, -0.96391318, -0.43208909,  1.78974086,
        0.00127969, -0.10049141,  0.07141173, -0.12979596]

[ 0.60972266,  0.93551155,  0.96907989,  0.88097057,  0.86936422,
        1.11777998,  0.67621476,  0.07679443,  1.63857747,  0.48581496,
        0.89420527,  1.01222521, -0.78181436, -0.40707423,  1.662051  ,
        0.01433212,  0.16742863,  0.02175434, -0.18035759]

[ 0.62059676,  0.88384136,  0.93728196,  0.86372505,  0.8892517 ,
        1.0132939 ,  0.66340899,  0.05368954,  1.65424001,  0.40125662,
        0.71989726,  1.01632325, -0.9081898 , -0.30834051,  1.63922168,
        0.29146124, -0.22293418,  0.11110411, -0.13208529]

[ 0.66890592,  0.84527729,  0.97177966,  0.84784582,  0.88300861,
        1.01745893,  0.64501173,  0.10810368,  1.64252493,  0.42627394,
        0.74721329,  1.02668771, -0.8480979 , -0.41713759,  2.02368583,
        0.00097173, -0.06679875, -0.23305001,  0.48973201]

#### test the data format

In [106]:
temp = np.array([0.60319551,  0.85670162,  0.95154853,  0.88269402,  0.86424006,
        1.04898076,  0.67292837,  0.087896  ,  1.52545837,  0.55680651,
        0.80771379,  1.02972063, -0.85833905, -0.52554665,  1.71641269,
        0.00707366, -0.023854  , -0.09192209, -0.04326849])

In [107]:
temp[0:8]

array([0.60319551, 0.85670162, 0.95154853, 0.88269402, 0.86424006,
       1.04898076, 0.67292837, 0.087896  ])

In [108]:
temp[8:15]

array([ 1.52545837,  0.55680651,  0.80771379,  1.02972063, -0.85833905,
       -0.52554665,  1.71641269])

In [114]:
np.matmul(temp[15:19], np.array([[1, 0, 0, 0],[0, 0, 0, 1],[0, 1, 0, 0],[0, 0, 1, 0]]))

array([ 0.00707366, -0.09192209, -0.04326849, -0.023854  ])

In [115]:
temp[15:19]

array([ 0.00707366, -0.023854  , -0.09192209, -0.04326849])